---
  - name: install dependencies
    apt: name={{ item }} state=present
    tags: packer
    with_items:
       - unzip

  - name:
    tags: packer
    get_url: url="https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip" dest=/tmp/packer.zip

  - name: unzip packer
    unarchive: src=/tmp/packer.zip dest=/tmp/
    tags: packer

  - name: copy packer executable to bin
    copy:
      src: /tmp/packer
      dest: /bin/packer
      owner: root
      group: root
      mode: 0755

  - name: build an image with packer web2
    shell: packer build /vagrant/provisioning/packer/web2/packer.web2.json
    tags: packer

  - name: build an image with packer web3 for salt master
    shell: packer build /vagrant/provisioning/packer/web3/packer.web3.salt.master.json
    tags: packer

  - name: build an image with packer web3 for salt minion
    shell: packer build /vagrant/provisioning/packer/web3/packer.web3.salt.minion.json
    tags: packer
